# Generated by Django 2.0 on 2018-05-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
    ]
