# Generated by Django 2.0 on 2018-05-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_auto_20180531_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
