# Generated by Django 2.0 on 2018-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_auto_20180531_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
