# Generated by Django 2.0 on 2018-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_auto_20180531_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='lat',
            field=models.FloatField(default=59.93863),
        ),
        migrations.AddField(
            model_name='parent',
            name='lng',
            field=models.FloatField(default=30.31413),
        ),
    ]
