# Generated by Django 2.0 on 2018-06-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0009_auto_20180603_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adm_comment',
            field=models.TextField(default=''),
        ),
    ]
