# Generated by Django 2.0 on 2018-06-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0010_profile_adm_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adm_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
