# Generated by Django 2.0 on 2018-06-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0014_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.SlugField(max_length=15),
        ),
    ]
