# Generated by Django 2.0 on 2018-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0019_kid_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
