# Generated by Django 2.0 on 2018-06-06 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0020_profile_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default='1', max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('face1', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('face2', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('face3', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('location', models.SlugField(default='1', max_length=15)),
                ('letter', models.TextField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
