# Generated by Django 2.0 on 2018-06-06 18:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0022_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
        migrations.AddField(
            model_name='course',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(blank=True), blank=True, null=True, size=5),
        ),
    ]
