# Generated by Django 2.0 on 2018-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0023_auto_20180606_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('0', 'начинающие'), ('1', 'продолжающие'), ('2', 'продвинутые'), ('3', 'чемпионы')], default='0', max_length=1),
        ),
    ]
