# Generated by Django 2.0 on 2018-06-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0026_auto_20180607_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(to='land.Subject'),
        ),
    ]
