# Generated by Django 2.0 on 2018-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0027_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='web',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
