# Generated by Django 2.0 on 2018-06-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0028_place_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.RemoveField(
            model_name='course',
            name='locations',
        ),
        migrations.AddField(
            model_name='course',
            name='locations',
            field=models.ManyToManyField(to='land.Location'),
        ),
        migrations.RemoveField(
            model_name='kid',
            name='locations',
        ),
        migrations.AddField(
            model_name='kid',
            name='locations',
            field=models.ManyToManyField(to='land.Location'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='username',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='place',
            name='code',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.Location'),
        ),
    ]
