# Generated by Django 2.0 on 2018-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0029_auto_20180612_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='locations',
            field=models.ManyToManyField(null=True, to='land.Location'),
        ),
    ]
