# Generated by Django 2.0 on 2018-06-17 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0031_auto_20180614_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('B', 'беби-ситтер'), ('R', 'репетитор'), ('T', 'целевая группа'), ('D', 'группа общего развития')], default='B', max_length=1)),
                ('kids', models.ManyToManyField(to='land.Kid')),
                ('locations', models.ManyToManyField(to='land.Location')),
                ('subjects', models.ManyToManyField(to='land.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('B', 'беби-ситтер'), ('R', 'репетитор')], default='B', max_length=1)),
                ('locations', models.ManyToManyField(to='land.Location')),
                ('subjects', models.ManyToManyField(to='land.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
