# Generated by Django 2.0 on 2018-06-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0032_claim_prop'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='letter',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='prop',
            name='letter',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
