# Generated by Django 2.0 on 2018-06-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0033_auto_20180617_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prop',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='choices',
            field=models.CharField(choices=[('B', 'беби-ситтер'), ('R', 'репетитор'), ('C', 'консультант по сети'), ('T', 'целевая группа'), ('D', 'группа общего развития')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='prop',
            name='choices',
            field=models.CharField(choices=[('B', 'беби-ситтер'), ('R', 'репетитор'), ('C', 'консультант по сети')], default='B', max_length=1),
        ),
    ]
