# Generated by Django 2.0 on 2018-06-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0035_auto_20180618_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pref_addr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pref_kid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.Kid'),
        ),
    ]
