# Generated by Django 2.0 on 2018-06-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0036_auto_20180620_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='prop',
            name='locations',
        ),
        migrations.AddField(
            model_name='claim',
            name='kid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.Kid'),
        ),
        migrations.AddField(
            model_name='claim',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.Location'),
        ),
        migrations.AddField(
            model_name='prop',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.Location'),
        ),
    ]
