# Generated by Django 2.0 on 2018-06-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0037_auto_20180621_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.Location'),
        ),
        migrations.AlterField(
            model_name='prop',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.Location'),
        ),
    ]
