# Generated by Django 2.0 on 2018-06-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0039_auto_20180621_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='land.Subject'),
        ),
    ]
