# Generated by Django 2.0 on 2018-06-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0042_remove_prop_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='obj_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
