# Generated by Django 2.0 on 2018-06-23 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0042_remove_prop_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
