# Generated by Django 2.0 on 2018-07-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0044_auto_20180703_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='interest',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ask_justme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_justme',
            field=models.BooleanField(default=False),
        ),
    ]
