# Generated by Django 2.0 on 2018-07-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0045_auto_20180708_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='letter',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
