# Generated by Django 2.0 on 2018-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0048_event_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('0', 'неизвестно'), ('1', 'помню'), ('2', 'наблюдаю'), ('3', 'участвую')], default='0', max_length=1),
        ),
    ]
