# Generated by Django 2.0 on 2018-07-29 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0049_auto_20180721_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='QLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.BooleanField(default=False)),
                ('letter', models.TextField(blank=True, max_length=250, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('line_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.BooleanField(default=False)),
                ('letter', models.TextField(max_length=250)),
                ('option_number', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.QLine')),
            ],
        ),
        migrations.CreateModel(
            name='QPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('letter', models.TextField(blank=True, max_length=250, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qline',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.QPage'),
        ),
    ]
