# Generated by Django 2.0 on 2018-07-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0050_auto_20180729_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='qline',
            name='code',
            field=models.CharField(default='?', max_length=30),
        ),
        migrations.AddField(
            model_name='qline',
            name='type',
            field=models.CharField(choices=[('1', 'эссе'), ('2', 'да-нет'), ('3', 'варианты')], default='2', max_length=1),
        ),
    ]
