# Generated by Django 2.0 on 2018-07-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0051_auto_20180730_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='page1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.QPage'),
        ),
    ]
