# Generated by Django 2.0 on 2018-07-31 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0053_invite_page1_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='APage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField(blank=True, max_length=1000, null=True)),
                ('written', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.Event')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land.QPage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
