# Generated by Django 2.0 on 2018-07-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0054_apage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qoption',
            name='hide',
        ),
    ]
